// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Capture from "./Capture.res.js";

function parseMode(modeStr) {
  if (modeStr === undefined) {
    return "Quick";
  }
  switch (modeStr) {
    case "full" :
        return "Full";
    case "template" :
        return "Template";
    default:
      return "Quick";
  }
}

async function main() {
  var mode = parseMode(process.argv[2]);
  var session = Capture.CaptureSession.make(mode, undefined);
  var result = await Capture.CaptureSession.capture(session);
  if (result.TAG === "Ok") {
    console.log("\n✅ Success! Experience ID: " + result._0);
    process.exit(0);
    return ;
  }
  console.error("\n❌ Error: " + result._0);
  process.exit(1);
}

main();

export {
  parseMode ,
  main ,
}
/*  Not a pure module */
