// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__JSON from "@rescript/core/src/Core__JSON.res.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as Core__Result from "@rescript/core/src/Core__Result.res.js";

function getString(json, field) {
  var obj = Core__JSON.Decode.object(json);
  if (obj === undefined) {
    return {
            TAG: "Error",
            _0: "Expected JSON object"
          };
  }
  var value = obj[field];
  if (value === undefined) {
    return {
            TAG: "Error",
            _0: "Missing field \"" + field + "\""
          };
  }
  var str = Core__JSON.Decode.string(value);
  if (str !== undefined) {
    return {
            TAG: "Ok",
            _0: str
          };
  } else {
    return {
            TAG: "Error",
            _0: "Field \"" + field + "\" is not a string"
          };
  }
}

function getOptionalString(json, field) {
  return Core__Option.flatMap(Core__Option.flatMap(Core__JSON.Decode.object(json), (function (obj) {
                    return obj[field];
                  })), Core__JSON.Decode.string);
}

function getArray(json, field) {
  var obj = Core__JSON.Decode.object(json);
  if (obj === undefined) {
    return {
            TAG: "Error",
            _0: "Expected JSON object"
          };
  }
  var value = obj[field];
  if (value === undefined) {
    return {
            TAG: "Ok",
            _0: []
          };
  }
  var arr = Core__JSON.Decode.array(value);
  if (arr !== undefined) {
    return {
            TAG: "Ok",
            _0: arr
          };
  } else {
    return {
            TAG: "Error",
            _0: "Field \"" + field + "\" is not an array"
          };
  }
}

function getOptionalArray(json, field) {
  return Core__Option.flatMap(Core__Option.flatMap(Core__JSON.Decode.object(json), (function (obj) {
                    return obj[field];
                  })), Core__JSON.Decode.array);
}

function getObject(json, field) {
  var obj = Core__JSON.Decode.object(json);
  if (obj === undefined) {
    return {
            TAG: "Error",
            _0: "Expected JSON object"
          };
  }
  var value = obj[field];
  if (value !== undefined) {
    return {
            TAG: "Ok",
            _0: value
          };
  } else {
    return {
            TAG: "Error",
            _0: "Missing field \"" + field + "\""
          };
  }
}

function getOptionalObject(json, field) {
  return Core__Option.flatMap(Core__JSON.Decode.object(json), (function (obj) {
                return obj[field];
              }));
}

function getNumber(json, field) {
  var obj = Core__JSON.Decode.object(json);
  if (obj === undefined) {
    return {
            TAG: "Error",
            _0: "Expected JSON object"
          };
  }
  var value = obj[field];
  if (value === undefined) {
    return {
            TAG: "Error",
            _0: "Missing field \"" + field + "\""
          };
  }
  var num = Core__JSON.Decode.$$float(value);
  if (num !== undefined) {
    return {
            TAG: "Ok",
            _0: num
          };
  } else {
    return {
            TAG: "Error",
            _0: "Field \"" + field + "\" is not a number"
          };
  }
}

function getOptionalNumber(json, field) {
  return Core__Option.flatMap(Core__Option.flatMap(Core__JSON.Decode.object(json), (function (obj) {
                    return obj[field];
                  })), Core__JSON.Decode.$$float);
}

function decodeCoordinates(json) {
  var match = getNumber(json, "latitude");
  var match$1 = getNumber(json, "longitude");
  if (match.TAG === "Ok") {
    if (match$1.TAG === "Ok") {
      return {
              TAG: "Ok",
              _0: {
                latitude: match._0,
                longitude: match$1._0
              }
            };
    } else {
      return {
              TAG: "Error",
              _0: "Coordinates decode error: " + match$1._0
            };
    }
  } else {
    return {
            TAG: "Error",
            _0: "Coordinates decode error: " + match._0
          };
  }
}

function decodeLocation(json) {
  var err = getString(json, "name");
  if (err.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: "Location decode error: " + err._0
          };
  }
  var coordinates = Core__Option.flatMap(getOptionalObject(json, "coordinates"), (function (coordJson) {
          var coords = decodeCoordinates(coordJson);
          if (coords.TAG === "Ok") {
            return coords._0;
          }
          
        }));
  var type_ = getOptionalString(json, "type");
  var address = getOptionalString(json, "address");
  return {
          TAG: "Ok",
          _0: {
            name: err._0,
            coordinates: coordinates,
            type: type_,
            address: address
          }
        };
}

function decodeLearner(json) {
  var err = getString(json, "id");
  if (err.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: "Learner decode error: " + err._0
          };
  }
  var name = getOptionalString(json, "name");
  var interests = Core__Option.map(getOptionalArray(json, "interests"), (function (arr) {
          return Core__Array.filterMap(arr.map(Core__JSON.Decode.string), (function (x) {
                        return x;
                      }));
        }));
  return {
          TAG: "Ok",
          _0: {
            id: err._0,
            name: name,
            interests: interests
          }
        };
}

function decodeContext(json) {
  var err = getObject(json, "location");
  if (err.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: "Context decode error: " + err._0
          };
  }
  var err$1 = decodeLocation(err._0);
  if (err$1.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: "Context.location decode error: " + err$1._0
          };
  }
  var situation = getOptionalString(json, "situation");
  var connections = Core__Option.map(getOptionalArray(json, "connections"), (function (arr) {
          return Core__Array.filterMap(arr.map(Core__JSON.Decode.string), (function (x) {
                        return x;
                      }));
        }));
  var timeOfDay = Core__Option.map(getOptionalString(json, "timeOfDay"), (function (str) {
          switch (str) {
            case "afternoon" :
                return "afternoon";
            case "evening" :
                return "evening";
            case "morning" :
                return "morning";
            default:
              return "night";
          }
        }));
  return {
          TAG: "Ok",
          _0: {
            location: err$1._0,
            situation: situation,
            connections: connections,
            timeOfDay: timeOfDay
          }
        };
}

function decodeOutcome(json) {
  var success = Core__Option.flatMap(Core__Option.flatMap(Core__JSON.Decode.object(json), (function (obj) {
              return obj["success"];
            })), Core__JSON.Decode.bool);
  var connections_made = Core__Option.map(getOptionalArray(json, "connections_made"), (function (arr) {
          return Core__Array.filterMap(arr.map(Core__JSON.Decode.string), (function (x) {
                        return x;
                      }));
        }));
  var next_questions = Core__Option.map(getOptionalArray(json, "next_questions"), (function (arr) {
          return Core__Array.filterMap(arr.map(Core__JSON.Decode.string), (function (x) {
                        return x;
                      }));
        }));
  var artifacts = Core__Option.map(getOptionalArray(json, "artifacts"), (function (arr) {
          return Core__Array.filterMap(arr.map(Core__JSON.Decode.string), (function (x) {
                        return x;
                      }));
        }));
  return {
          TAG: "Ok",
          _0: {
            success: success,
            connections_made: connections_made,
            next_questions: next_questions,
            artifacts: artifacts
          }
        };
}

function decodeExperienceData(json) {
  var err = getString(json, "type");
  if (err.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: "ExperienceData decode error: " + err._0
          };
  }
  var err$1 = getString(json, "description");
  if (err$1.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: "ExperienceData.description decode error: " + err$1._0
          };
  }
  var domains = Core__Option.map(getOptionalArray(json, "domains"), (function (arr) {
          return Core__Array.filterMap(arr.map(Core__JSON.Decode.string), (function (x) {
                        return x;
                      }));
        }));
  var outcome = Core__Option.flatMap(getOptionalObject(json, "outcome"), (function (outcomeJson) {
          var out = decodeOutcome(outcomeJson);
          if (out.TAG === "Ok") {
            return out._0;
          }
          
        }));
  var duration = Core__Option.map(getOptionalNumber(json, "duration"), (function (prim) {
          return prim | 0;
        }));
  var intensity = Core__Option.map(getOptionalString(json, "intensity"), (function (str) {
          switch (str) {
            case "low" :
                return "low";
            case "medium" :
                return "medium";
            default:
              return "high";
          }
        }));
  return {
          TAG: "Ok",
          _0: {
            type: err._0,
            description: err$1._0,
            domains: domains,
            outcome: outcome,
            duration: duration,
            intensity: intensity
          }
        };
}

function decodePrivacy(json) {
  var err = getString(json, "level");
  if (err.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: "Privacy decode error: " + err._0
          };
  }
  var level;
  switch (err._0) {
    case "anonymous" :
        level = "anonymous";
        break;
    case "private" :
        level = "private";
        break;
    default:
      level = "public";
  }
  var shareableWith = Core__Option.map(getOptionalArray(json, "shareableWith"), (function (arr) {
          return Core__Array.filterMap(arr.map(Core__JSON.Decode.string), (function (x) {
                        return x;
                      }));
        }));
  return {
          TAG: "Ok",
          _0: {
            level: level,
            shareableWith: shareableWith
          }
        };
}

function decodeLearningExperience(json) {
  var idResult = getString(json, "id");
  var timestampResult = getString(json, "timestamp");
  var versionResult = getString(json, "version");
  var learnerResult = Core__Result.flatMap(getObject(json, "learner"), decodeLearner);
  var contextResult = Core__Result.flatMap(getObject(json, "context"), decodeContext);
  var experienceResult = Core__Result.flatMap(getObject(json, "experience"), decodeExperienceData);
  var err;
  if (idResult.TAG === "Ok") {
    if (timestampResult.TAG === "Ok") {
      if (versionResult.TAG === "Ok") {
        if (learnerResult.TAG === "Ok") {
          if (contextResult.TAG === "Ok") {
            if (experienceResult.TAG === "Ok") {
              var privacy = Core__Option.flatMap(getOptionalObject(json, "privacy"), (function (privJson) {
                      var priv = decodePrivacy(privJson);
                      if (priv.TAG === "Ok") {
                        return priv._0;
                      }
                      
                    }));
              var tags = Core__Option.map(getOptionalArray(json, "tags"), (function (arr) {
                      return Core__Array.filterMap(arr.map(Core__JSON.Decode.string), (function (x) {
                                    return x;
                                  }));
                    }));
              return {
                      TAG: "Ok",
                      _0: {
                        id: idResult._0,
                        timestamp: timestampResult._0,
                        learner: learnerResult._0,
                        context: contextResult._0,
                        experience: experienceResult._0,
                        privacy: privacy,
                        tags: tags,
                        version: versionResult._0
                      }
                    };
            }
            err = experienceResult._0;
          } else {
            err = contextResult._0;
          }
        } else {
          err = learnerResult._0;
        }
      } else {
        err = versionResult._0;
      }
    } else {
      err = timestampResult._0;
    }
  } else {
    err = idResult._0;
  }
  return {
          TAG: "Error",
          _0: "LearningExperience decode error: " + err
        };
}

function decodeExperiences(jsonArray) {
  var experiences = [];
  var errors = [];
  jsonArray.forEach(function (json, i) {
        var exp = decodeLearningExperience(json);
        if (exp.TAG === "Ok") {
          experiences.push(exp._0);
          return ;
        }
        errors.push("Experience " + i.toString() + ": " + exp._0);
      });
  if (errors.length > 0) {
    return {
            TAG: "Error",
            _0: "Failed to decode " + errors.length.toString() + " experiences:\n" + errors.join("\n")
          };
  } else {
    return {
            TAG: "Ok",
            _0: experiences
          };
  }
}

export {
  getString ,
  getOptionalString ,
  getArray ,
  getOptionalArray ,
  getObject ,
  getOptionalObject ,
  getNumber ,
  getOptionalNumber ,
  decodeCoordinates ,
  decodeLocation ,
  decodeLearner ,
  decodeContext ,
  decodeOutcome ,
  decodeExperienceData ,
  decodePrivacy ,
  decodeLearningExperience ,
  decodeExperiences ,
}
/* No side effect */
