// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function exportToCSV(experiences) {
  var headers = [
    "id",
    "timestamp",
    "learner_id",
    "location",
    "type",
    "description",
    "domains",
    "success",
    "latitude",
    "longitude"
  ];
  var rows = [headers.join(",")];
  experiences.forEach(function (exp) {
        var locationName = exp.context.location.name;
        var description = exp.experience.description.replaceAll("\"", "\"\"");
        var domains = Core__Option.getOr(exp.experience.domains, []).join("; ");
        var success = Core__Option.getOr(Core__Option.map(Core__Option.flatMap(exp.experience.outcome, (function (o) {
                        return o.success;
                      })), (function (b) {
                    if (b) {
                      return "true";
                    } else {
                      return "false";
                    }
                  })), "");
        var latitude = Core__Option.getOr(Core__Option.map(exp.context.location.coordinates, (function (c) {
                    return c.latitude.toString();
                  })), "");
        var longitude = Core__Option.getOr(Core__Option.map(exp.context.location.coordinates, (function (c) {
                    return c.longitude.toString();
                  })), "");
        var row = [
          exp.id,
          exp.timestamp,
          exp.learner.id,
          "\"" + locationName + "\"",
          exp.experience.type,
          "\"" + description + "\"",
          "\"" + domains + "\"",
          success,
          latitude,
          longitude
        ];
        rows.push(row.join(","));
      });
  return rows.join("\n");
}

function exportToGeoJSON(experiences) {
  var locationExps = Core__Array.reduce(experiences, {}, (function (acc, exp) {
          var $$location = exp.context.location.name;
          var exps = Core__Option.getOr(acc[$$location], []);
          acc[$$location] = exps.concat([exp]);
          return acc;
        }));
  var features = [];
  Object.entries(locationExps).forEach(function (param) {
        var exps = param[1];
        var coordsOpt = exps.find(function (exp) {
              return Core__Option.isSome(exp.context.location.coordinates);
            });
        if (coordsOpt === undefined) {
          return ;
        }
        var coords = coordsOpt.context.location.coordinates;
        if (coords === undefined) {
          return ;
        }
        var domains = Core__Array.reduce(Core__Array.reduce(exps, [], (function (acc, e) {
                    var doms = e.experience.domains;
                    if (doms !== undefined) {
                      return acc.concat(doms);
                    } else {
                      return acc;
                    }
                  })), [], (function (acc, d) {
                if (acc.includes(d)) {
                  return acc;
                } else {
                  return acc.concat([d]);
                }
              }));
        var geometry_coordinates = [
          coords.longitude,
          coords.latitude
        ];
        var geometry = {
          type: "Point",
          coordinates: geometry_coordinates
        };
        var properties_name = param[0];
        var properties_experiences = exps.length;
        var properties = {
          name: properties_name,
          experiences: properties_experiences,
          domains: domains
        };
        var feature = {
          type: "Feature",
          geometry: geometry,
          properties: properties
        };
        features.push(feature);
      });
  return {
          type: "FeatureCollection",
          features: features
        };
}

function exportToDOT(experiences) {
  var domainCounts = {};
  var coOccurrences = {};
  experiences.forEach(function (exp) {
        var domains = exp.experience.domains;
        if (domains !== undefined) {
          domains.forEach(function (d) {
                var count = Core__Option.getOr(domainCounts[d], 0);
                domainCounts[d] = count + 1 | 0;
              });
          domains.forEach(function (d1) {
                domains.forEach(function (d2) {
                      if (d1 >= d2) {
                        return ;
                      }
                      var key = d1 + "--" + d2;
                      var count = Core__Option.getOr(coOccurrences[key], 0);
                      coOccurrences[key] = count + 1 | 0;
                    });
              });
          return ;
        }
        
      });
  var lines = [
    "graph DomainNetwork {",
    "  layout=neato;",
    "  overlap=false;",
    ""
  ];
  Object.entries(domainCounts).forEach(function (param) {
        var size = Math.max(0.5, Math.min(3.0, param[1] / 5.0)).toString();
        lines.push("  \"" + param[0] + "\" [width=" + size + "];");
      });
  lines.push("");
  Object.entries(coOccurrences).forEach(function (param) {
        var parts = param[0].split("--");
        var source = Core__Option.getOr(parts[0], "");
        var target = Core__Option.getOr(parts[1], "");
        var penwidth = Math.max(1.0, Math.min(5.0, param[1])).toString();
        lines.push("  \"" + source + "\" -- \"" + target + "\" [penwidth=" + penwidth + "];");
      });
  lines.push("}");
  return lines.join("\n");
}

function exportJourneysToMarkdown(experiences) {
  var lines = [
    "# UbiCity Learner Journeys",
    ""
  ];
  var learnerExps = Core__Array.reduce(experiences, {}, (function (acc, exp) {
          var learnerId = exp.learner.id;
          var exps = Core__Option.getOr(acc[learnerId], []);
          acc[learnerId] = exps.concat([exp]);
          return acc;
        }));
  Object.entries(learnerExps).forEach(function (param) {
        var exps = param[1];
        lines.push("## Learner: " + param[0]);
        lines.push("");
        lines.push("**Total Experiences:** " + exps.length.toString());
        lines.push("");
        var sorted = exps.toSorted(function (a, b) {
              if (a.timestamp < b.timestamp) {
                return -1.0;
              } else {
                return 1.0;
              }
            });
        lines.push("### Timeline");
        lines.push("");
        sorted.forEach(function (exp, i) {
              var date = new Date(exp.timestamp).toLocaleDateString();
              var $$location = exp.context.location.name;
              var type_ = exp.experience.type;
              var description = exp.experience.description;
              lines.push((i + 1 | 0).toString() + ". **" + date + "** - " + $$location + " (" + type_ + ")");
              var domains = exp.experience.domains;
              if (domains !== undefined && domains.length > 0) {
                lines.push("   - Domains: " + domains.join(", "));
              }
              lines.push("   - " + description);
              lines.push("");
            });
        var questions = Core__Array.reduce(sorted, [], (function (acc, exp) {
                var outcome = exp.experience.outcome;
                if (outcome === undefined) {
                  return acc;
                }
                var qs = outcome.next_questions;
                if (qs !== undefined) {
                  return acc.concat(qs);
                } else {
                  return acc;
                }
              }));
        if (questions.length > 0) {
          lines.push("### Questions Emerged");
          lines.push("");
          questions.forEach(function (q) {
                lines.push("- " + q);
              });
          lines.push("");
        }
        lines.push("---");
        lines.push("");
      });
  return lines.join("\n");
}

function exportToJSON(experiences) {
  var jsObjects = experiences.map(function (exp) {
        return {
                id: exp.id,
                timestamp: exp.timestamp,
                version: exp.version,
                learner: {
                  id: exp.learner.id,
                  name: exp.learner.name,
                  interests: exp.learner.interests
                },
                context: {
                  location: {
                    name: exp.context.location.name,
                    coordinates: exp.context.location.coordinates,
                    type: exp.context.location.type,
                    address: exp.context.location.address
                  },
                  situation: exp.context.situation,
                  connections: exp.context.connections,
                  timeOfDay: exp.context.timeOfDay
                },
                experience: {
                  type: exp.experience.type,
                  description: exp.experience.description,
                  domains: exp.experience.domains,
                  outcome: exp.experience.outcome,
                  duration: exp.experience.duration,
                  intensity: exp.experience.intensity
                },
                privacy: exp.privacy,
                tags: exp.tags
              };
      });
  var json = JSON.stringify(jsObjects);
  if (json !== undefined) {
    return json;
  } else {
    return "[]";
  }
}

function exportData(experiences, format) {
  switch (format) {
    case "CSV" :
        return exportToCSV(experiences);
    case "GeoJSON" :
        var geoJSON = exportToGeoJSON(experiences);
        var json = JSON.stringify(geoJSON);
        if (json !== undefined) {
          return json;
        } else {
          return "{\"type\":\"FeatureCollection\",\"features\":[]}";
        }
    case "DOT" :
        return exportToDOT(experiences);
    case "Markdown" :
        return exportJourneysToMarkdown(experiences);
    case "JSON" :
        return exportToJSON(experiences);
    
  }
}

export {
  exportToCSV ,
  exportToGeoJSON ,
  exportToDOT ,
  exportJourneysToMarkdown ,
  exportToJSON ,
  exportData ,
}
/* No side effect */
