// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Crypto from "crypto";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

var $$Crypto$1 = {};

function hashString(str) {
  var hash = 5381;
  for(var i = 0 ,i_finish = str.length; i < i_finish; ++i){
    var $$char = str.charCodeAt(i) | 0;
    var shifted = Math.imul(hash, 33);
    hash = shifted + $$char | 0;
  }
  return Math.abs(hash).toString(16).slice(0, 8);
}

function sanitizeText(text) {
  var sanitized = text.length > 10000 ? text.slice(0, 10000) : text;
  var sanitized$1 = sanitized.replace(/[\w.-]+@[\w.-]+\.[a-zA-Z]{2,}/g, "[email]");
  var sanitized$2 = sanitized$1.replace(/\b\d{3}[-.]?\d{3}[-.]?\d{4}\b/g, "[phone]");
  var sanitized$3 = sanitized$2.replace(/https?:\/\/[^\s]{1,2000}/g, "[url]");
  return sanitized$3.replace(/\b(I met|met with|talked to|spoke with)\s+([A-Z][a-z]+)\b/g, "$1 [person]");
}

function anonymizeLearner(experience, options) {
  var opts = Core__Option.getOr(options, {
        preserveIds: false,
        hashIds: true,
        removeName: true,
        removeInterests: false
      });
  var newLearnerId = opts.preserveIds ? experience.learner.id : (
      opts.hashIds ? "anon-" + hashString(experience.learner.id) : "anon-" + $$Crypto.randomUUID().slice(0, 8)
    );
  var newName = opts.removeName ? undefined : experience.learner.name;
  var newInterests = opts.removeInterests ? undefined : experience.learner.interests;
  return {
          id: experience.id,
          timestamp: experience.timestamp,
          learner: {
            id: newLearnerId,
            name: newName,
            interests: newInterests
          },
          context: experience.context,
          experience: experience.experience,
          privacy: experience.privacy,
          tags: experience.tags,
          version: experience.version
        };
}

function anonymizeLocation(experience, options) {
  var opts = Core__Option.getOr(options, {
        fuzzyCoordinates: true,
        fuzzRadius: 0.01,
        removeAddress: true,
        generalizeType: false
      });
  var coords = experience.context.location.coordinates;
  var newCoordinates;
  if (coords !== undefined && opts.fuzzyCoordinates) {
    var latitude = Math.round(coords.latitude / opts.fuzzRadius) * opts.fuzzRadius;
    var longitude = Math.round(coords.longitude / opts.fuzzRadius) * opts.fuzzRadius;
    newCoordinates = {
      latitude: latitude,
      longitude: longitude
    };
  } else {
    newCoordinates = coords;
  }
  var newAddress = opts.removeAddress ? undefined : experience.context.location.address;
  var t = experience.context.location.type;
  var newType;
  if (t !== undefined && opts.generalizeType) {
    var generalizations = Object.fromEntries([
          [
            "coffee shop",
            "cafe"
          ],
          [
            "starbucks",
            "cafe"
          ],
          [
            "library branch",
            "library"
          ],
          [
            "community college",
            "educational institution"
          ],
          [
            "university",
            "educational institution"
          ]
        ]);
    var lower = t.toLowerCase();
    newType = Core__Option.getOr(generalizations[lower], t);
  } else {
    newType = t;
  }
  var init = experience.context;
  var init$1 = experience.context.location;
  return {
          id: experience.id,
          timestamp: experience.timestamp,
          learner: experience.learner,
          context: {
            location: {
              name: init$1.name,
              coordinates: newCoordinates,
              type: newType,
              address: newAddress
            },
            situation: init.situation,
            connections: init.connections,
            timeOfDay: init.timeOfDay
          },
          experience: experience.experience,
          privacy: experience.privacy,
          tags: experience.tags,
          version: experience.version
        };
}

function removePII(experience) {
  var conns = experience.context.connections;
  var newConnections = conns !== undefined ? conns.map(function (_name, i) {
          return "person-" + (i + 1 | 0).toString();
        }) : undefined;
  var newDescription = sanitizeText(experience.experience.description);
  var outcome = experience.experience.outcome;
  var newOutcome = outcome !== undefined ? ({
        success: outcome.success,
        connections_made: Core__Option.map(outcome.connections_made, (function (arr) {
                return arr.map(sanitizeText);
              })),
        next_questions: Core__Option.map(outcome.next_questions, (function (arr) {
                return arr.map(sanitizeText);
              })),
        artifacts: outcome.artifacts
      }) : undefined;
  var init = experience.context;
  var init$1 = experience.experience;
  return {
          id: experience.id,
          timestamp: experience.timestamp,
          learner: experience.learner,
          context: {
            location: init.location,
            situation: init.situation,
            connections: newConnections,
            timeOfDay: init.timeOfDay
          },
          experience: {
            type: init$1.type,
            description: newDescription,
            domains: init$1.domains,
            outcome: newOutcome,
            duration: init$1.duration,
            intensity: init$1.intensity
          },
          privacy: experience.privacy,
          tags: experience.tags,
          version: experience.version
        };
}

function fullyAnonymize(experience, options) {
  var opts = Core__Option.getOr(options, {
        learner: undefined,
        location: undefined
      });
  var result = anonymizeLearner(experience, opts.learner);
  var result$1 = anonymizeLocation(result, opts.location);
  var result$2 = removePII(result$1);
  return {
          id: result$2.id,
          timestamp: result$2.timestamp,
          learner: result$2.learner,
          context: result$2.context,
          experience: result$2.experience,
          privacy: {
            level: "anonymous",
            shareableWith: undefined
          },
          tags: result$2.tags,
          version: result$2.version
        };
}

function filterByPrivacyLevel(experiences, includePrivateOpt, param) {
  var includePrivate = includePrivateOpt !== undefined ? includePrivateOpt : false;
  return experiences.filter(function (exp) {
              var match = exp.privacy;
              if (match !== undefined && match.level === "private") {
                return includePrivate;
              } else {
                return true;
              }
            });
}

function generateShareableDataset(experiences, includePrivateOpt, anonymizationLevelOpt, param) {
  var includePrivate = includePrivateOpt !== undefined ? includePrivateOpt : false;
  var anonymizationLevel = anonymizationLevelOpt !== undefined ? anonymizationLevelOpt : "Full";
  return filterByPrivacyLevel(experiences, includePrivate, undefined).map(function (exp) {
              switch (anonymizationLevel) {
                case "Full" :
                    return fullyAnonymize(exp, undefined);
                case "Partial" :
                    return anonymizeLearner(exp, undefined);
                case "None_" :
                    return exp;
                
              }
            });
}

export {
  $$Crypto$1 as $$Crypto,
  hashString ,
  sanitizeText ,
  anonymizeLearner ,
  anonymizeLocation ,
  removePII ,
  fullyAnonymize ,
  filterByPrivacyLevel ,
  generateShareableDataset ,
}
/* crypto Not a pure module */
