// Generated by AffineScript compiler (Deno-ESM target, issue #122)
// SPDX-License-Identifier: PMPL-1.0-or-later
// ---- AffineScript Deno-ESM runtime ----
const Some = (value) => ({ tag: "Some", value });
const None = { tag: "None" };
const Ok   = (value) => ({ tag: "Ok",  value });
const Err  = (error) => ({ tag: "Err", error });
const Unit = null;
const print   = (s) => { Deno.stdout.writeSync(new TextEncoder().encode(String(s))); };
const println = (s) => { console.log(String(s)); };
// ---- Deno host shims (extern fn lowering targets, issue #122) ----
// Kept tiny + inlined so emitted modules are genuinely drop-in (no extra
// package to publish or resolve). The same surface is mirrored, for
// standalone `deno test`, by packages/affine-deno/mod.js.
const __as_ensureDir = (p) => {
  try { Deno.mkdirSync(p, { recursive: true }); }
  catch (e) { if (!(e instanceof Deno.errors.AlreadyExists)) throw e; }
};
const __as_pathJoin = (a, b) => {
  if (a.length === 0) return b;
  const sep = a.endsWith("/") || a.endsWith("\\") ? "" : "/";
  return a + sep + b;
};
const __as_readDirNames = (p) => {
  const names = [];
  for (const entry of Deno.readDirSync(p)) {
    if (entry.isFile) names.push(entry.name);
  }
  return names;
};
const __as_isNotFound = (e) => (e instanceof Deno.errors.NotFound);
const __as_wasmInstance = (bytes) =>
  new WebAssembly.Instance(new WebAssembly.Module(bytes)).exports;
// `++` is overloaded (string concat / array concat); `a + b` would
// stringify arrays. Dispatch on shape so stdlib/string.affine's
// `result ++ [x]` and `a ++ b` are both correct.
const __as_concat = (a, b) => Array.isArray(a) ? a.concat(b) : (a + b);
// Honest host/runtime primitives underpinning the AffineScript-level
// stdlib/string.affine (its is_empty/starts_with/ends_with/split/join/
// replace/... are real AffineScript on top of these).
const __as_strSub = (s, start, n) => String(s).slice(start, start + n);
const __as_strGet = (s, i) => String(s)[i];
const __as_strFind = (s, n) => String(s).indexOf(n);
const __as_charToInt = (c) => String(c).codePointAt(0);
const __as_intToChar = (n) => String.fromCodePoint(n);
const __as_parseInt = (s) => {
  const n = parseInt(String(s), 10);
  return Number.isNaN(n) ? None : Some(n);
};
const __as_parseFloat = (s) => {
  const n = parseFloat(String(s));
  return Number.isNaN(n) ? None : Some(n);
};
const __as_show = (v) => (typeof v === "string" ? v : JSON.stringify(v));
// ---- end runtime ----

// type Json
export function has_json_ext(name) {
  const nl = ((name).length);
  if ((nl < 5)) { return false;  }
  return (__as_strSub(name, (nl - 5), 5) === ".json");
}

export function drop_json_ext(name) {
  return __as_strSub(name, 0, (((name).length) - 5));
}

export class ExperienceStorage {
  constructor(storageDir) {
    const dir = (storageDir ?? "./ubicity-data");
    this.storageDir = dir;
    this.experiencesDir = __as_pathJoin(dir, "experiences");
    this.mapsDir = __as_pathJoin(dir, "maps");
    this.analysesDir = __as_pathJoin(dir, "analyses");
  }
  async ensureDirectories() {
    __as_ensureDir(this.storageDir);
    __as_ensureDir(this.experiencesDir);
    __as_ensureDir(this.mapsDir);
    __as_ensureDir(this.analysesDir);
    return 0;
  }
  async saveExperience(experience) {
    (await this.ensureDirectories());
    const filename = __as_concat(String((experience)["id"]), ".json");
    const filepath = __as_pathJoin(this.experiencesDir, filename);
    Deno.writeTextFileSync(filepath, JSON.stringify(experience, null, 2));
    return filepath;
  }
  async loadExperience(id) {
    const filepath = __as_pathJoin(this.experiencesDir, __as_concat(id, ".json"));
    return (await (async () => { try { return (await (async () => { return JSON.parse(Deno.readTextFileSync(filepath)); return Unit; })()); } catch (__e) { const e = __e; return (__as_isNotFound(e) ? (await (async () => { return null; })()) : (await (async () => { return (() => { throw new Error(__as_concat("loadExperience: ", String((e)["message"]))); })(); })())); } })());
  }
  async loadAllExperiences() {
    return (await (async () => { try { return (await (async () => { (await this.ensureDirectories()); let acc = []; for (const name of __as_readDirNames(this.experiencesDir)) {  if (has_json_ext(name)) { const fp = __as_pathJoin(this.experiencesDir, name); acc = __as_concat(acc, [JSON.parse(Deno.readTextFileSync(fp))]);  } } return acc; return Unit; })()); } catch (__e) { const e = __e; return (__as_isNotFound(e) ? (await (async () => { return []; })()) : (await (async () => { return (() => { throw new Error("loadAllExperiences"); })(); })())); } })());
  }
  async deleteExperience(id) {
    const filepath = __as_pathJoin(this.experiencesDir, __as_concat(id, ".json"));
    return (await (async () => { try { return (await (async () => { Deno.removeSync(filepath); return true; return Unit; })()); } catch (__e) { const e = __e; return (__as_isNotFound(e) ? (await (async () => { return false; })()) : (await (async () => { return (() => { throw new Error("deleteExperience"); })(); })())); } })());
  }
  async saveReport(report, name) {
    (await this.ensureDirectories());
    const nm = (name ?? __as_concat(__as_concat("report-", String(Date.now())), ".json"));
    const filepath = __as_pathJoin(this.analysesDir, nm);
    Deno.writeTextFileSync(filepath, JSON.stringify(report, null, 2));
    return filepath;
  }
  async saveVisualization(html, name) {
    (await this.ensureDirectories());
    const nm = (name ?? "ubicity-map.html");
    const filepath = __as_pathJoin(this.storageDir, nm);
    Deno.writeTextFileSync(filepath, html);
    return filepath;
  }
  async listExperienceIds() {
    return (await (async () => { try { return (await (async () => { let ids = []; for (const name of __as_readDirNames(this.experiencesDir)) {  if (has_json_ext(name)) { ids = __as_concat(ids, [drop_json_ext(name)]);  } } return ids; return Unit; })()); } catch (__e) { const e = __e; return (__as_isNotFound(e) ? (await (async () => { return []; })()) : (await (async () => { return (() => { throw new Error("listExperienceIds"); })(); })())); } })());
  }
  async getStats() {
    const ids = (await this.listExperienceIds());
    const count = ((ids).length);
    let sizeAcc = 0;
    for (const id of ids) { const fp = __as_pathJoin(this.experiencesDir, __as_concat(id, ".json")); sizeAcc = (sizeAcc + Deno.statSync(fp).size); }
    return ({ totalExperiences: count, totalSizeBytes: sizeAcc, totalSizeKB: (Number(sizeAcc) / 1024).toFixed(2), storageDir: this.storageDir });
  }
}

// type Stats
